
    @startuml
    title Create Medication Record

    actor Client
    participant CareCompassUI
    participant AddMedicationAPI
    database Database

    Client -> CareCompassUI: request to add an medication
    CareCompassUI -> AddMedicationAPI: POST /medication
    AddMedicationAPI -> Database: Save an medication to Database

    Database  --> AddMedicationAPI: 200 response
    AddMedicationAPI --> CareCompassUI: 200 response
    CareCompassUI --> Client: Returns the newly created MedicationModel
    @enduml