@startuml
title Delete Vital Signs Record

actor Client
participant CareCompassUI
participant DeleteVitalSignsAPI
database Database

Client -> CareCompassUI: request to delete an medication
CareCompassUI -> DeleteVitalSignsAPI: DELETE /vitals/:vitalSignsId
DeleteVitalSignsAPI  -> Database: Deletes a specified vital signs record to Database

Database  --> DeleteVitalSignsAPI: 200 response
DeleteVitalSignsAPI --> CareCompassUI: 200 response
CareCompassUI --> Client: Show success message & details
@enduml