@startuml
title List All Notifications Vital Signs Records

actor Client
participant CareCompassUI
participant GetAllVitalSignsRecordsAPI
database Database

Client -> CareCompassUI: request to delete an medication
CareCompassUI -> GetAllVitalSignsRecordsAPI: GET /notification/user/:patientId
GetAllVitalSignsRecordsAPI -> Database: Retrieves all notifications set up for a specific user

Database  --> GetAllVitalSignsRecordsAPI: 200 response
GetAllVitalSignsRecordsAPI --> CareCompassUI: 200 response
CareCompassUI --> Client: List of NotificationModel entries
@enduml